# Generated by Django 5.1 on 2025-03-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0057_remove_notificacao_enviar_para_todos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
