# Generated by Django 5.1 on 2025-03-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0059_alter_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_celular',
            field=models.CharField(max_length=30),
        ),
    ]
